#!/usr/bin/env bash

# Simple shell script for symlinking all files from .rc dir to home directory
# Also upgrades, cleanups homebrew and similar stuff in single command
# Actually absurdly ugly, but hey, it works! Somehow.

# Array of all dotfiles, for example .bashrc
# Put them in array without leading dot. Directories is fine too
# All those arrays are used only one time (at initial deploy)
dotfiles=( ackrc bash_profile bashrc config/htop config/mc gemrc gitconfig
           gitignore_global htoprc mailcap mutt muttrc screenrc tigrc tmux.conf
           vim vimrc zshrc )

# linux-only dotfiles
linuxenv=( config/awesome config/openbox config/tint2 dircolors gvimrc
           local/share/themes toprc Xdefaults )

# homebrew packages
brewkegs=( ack android-platform-tools arping bash coreutils curl dhcpdump
           dnstracer docker docker-machine dos2unix ettercap findutils foremost
           git git-extras git-lfs git-secrets gnu-sed gnupg2 grep hadoop
           hashpump htop-osx httperf httpie httping httpry iperf3 john-jumbo lzo
           m-cli mitmproxy mobile-shell moreutils mtr mutt nmap openssh p7zip
           pwgen screen socat sqlite sqlmap sysdig tcpreplay tcptrace tig tmux
           unrar vim wget whois xz zsh zsh-completions )

# homebrew-cask packages
# Make sure that same cask-less app is not installed in /Applications
caskkegs=( alfred atom charles dropbox gns3 java netspot royal-tsx sequel-pro
           skype spectacle spotify teamspeak-client transmission visualvm vlc
           vmware-fusion wireshark xca xquartz )

# pyenv, rbenv, nodenv. Can also install their plugins.
# In fact, it can clone anything to anywhere
declare -A langenvs
langenvs=( [rbenv]=https://github.com/sstephenson/rbenv
           [rbenv/plugins/ruby-build]=https://github.com/sstephenson/ruby-build
           [pyenv]=https://github.com/yyuu/pyenv
           [nodenv]=https://github.com/OiNutter/nodenv
           [nodenv/plugins/node-build]=https://github.com/OiNutter/node-build )

# TBD: install this stuff somewhere in devenv
gems=( pry rubocop puppet-lint puppet )
pypi=( ptpython yapf jsbeautifier )

# Function to symlink dotfiles
# Checking if OS is Linux (GNU coreutils), if not, we assume OS uses BSD utils
symlink() {
  if [[ $(uname) == "Linux" ]]; then
    ln -sfvn $1 $2
  else
    ln -sfvh $1 $2
  fi
}

# Another ugly function for installing/updating py/nod/rb-envs. Still counts!
langenv() {
  if [[ -d ~/.$2 ]]; then
    echo "Updating ~/.$2"
    cd ~/.$2 && git pull
  else
    echo "Installing ~/.$2"
    git clone $1 ~/.$2
  fi
}

case "$1" in

  env)
    echo "Deploying environment"
    cd ~/.rc
    echo "Deploying dotfiles from `pwd` to ${HOME}"
    if [[ "$OSTYPE" =~ ^linux ]]; then
      dotdirs=( .config .local/share )
      for dir in ${dotdirs[@]}; do
        if [[ ! -d ~/${dir} ]]; then
          mkdir -p ~/${dir}
        fi
      done
      dotfiles=("${dotfiles[@]}" "${linuxenv[@]}")
    fi
    for file in ${dotfiles[@]}; do
      symlink ~/.rc/.${file} ~/.${file}
    done
    cd - >&/dev/null
    echo "Finished!"
  ;;

  # Install rb/py/node-env. Used just one time.
  # I can do that manually in 5m, but i'm too lazy.
  devenv)
    if [[ "$OSTYPE" =~ ^linux ]]; then
      echo "Make sure that following packages are installed:"
      echo "libssl-dev libreadline-dev zlib1g-dev libsqlite3-dev libbz2-dev"
    fi
    for target in "${!langenvs[@]}"; do
      langenv ${langenvs[$target]} $target
    done
    source ~/.rc/sh.d/S01_env
    for devenv in nodenv rbenv; do
      latest_version=$(${devenv} install -l | sed 's/^  //' | grep -e '[0-9].[0-9].[0-9]' | grep -v - | tail -1)
      ${devenv} install -s ${latest_version}
      ${devenv} global ${latest_version}
    done
    #pyenv is a little bit more tricky, since some apps still works only on 2.x. Yeah, i'm looking at you, fabric.
    python_versions=( $(pyenv install -l | grep -e '2.[0-9].[0-9]' | grep -v - | grep --invert-match 'dev\|a\|b' |tail -1)
                      $(pyenv install -l | grep -e '3.[0-9].[0-9]' | grep -v - | grep --invert-match 'dev\|a\|b' |tail -1) )
    for python in ${python_versions[@]}; do
      pyenv install -s $python
    done
    #defaults to 3.x
    pyenv global ${python_versions[1]}
  ;;

  homebrew)
    echo "Installing homebrew and favourite packages"
    #probably i should migrate to manual install.
    #Running (even respected) scripts from interwebs is stupid.
    if hash brew 2>/dev/null; then
      ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi
    for keg in ${brewkegs[@]}; do
      brew install ${keg}
    done
    for cask_keg in ${caskkegs[@]}; do
      brew cask install ${cask_keg}
    done
  ;;

  nuke)
    echo "Cleaning up env"
    echo "Removing dotfiles"
    for file in ${dotfiles[@]}; do
      rm -vf ~/.${file}
    done
    echo "Cleaning up devenv"
    rm -rvf ~/.pyenv
    rm -rvf ~/.rbenv
    rm -rvf ~/.nodenv
    echo "Removing history"
    rm -vf ~/.zsh-history
    rm -vf ~/.bash_history
    echo "Removing dotfiles directory"
    rm -rf ~/.rc
  ;;

  housekeeper)
    echo "Updating dotfiles repo"
    git -C ~/.rc pull
    echo "Cleaning up outdated symlinks"
    find -L $HOME -maxdepth 1 -type l -exec rm -i {} +
    if hash brew 2>/dev/null; then
      echo "Updating & cleaning up homebrew"
      brew update
      brew upgrade
      brew cleanup
      brew prune
      for app in $(brew cask list); do
        cver="$(brew cask info "${app}" | head -n 1 | cut -d " " -f 2)";
        ivers=$(ls -1 "/usr/local/Caskroom/${app}/.metadata/" | tr '\n' ' ' | sed -e 's/ $//');
        aivers=(${ivers});
        nvers=$(echo ${#aivers[@]});
        echo "[x] Found ${app} in cask list. Latest available version is ${cver}. You have installed version(s): ${ivers}";
        if [[ ${nvers} -eq 1 ]]; then
          echo "${ivers}" | grep -q "^${cver}$" && { echo "[x] Latest version already installed, skipping changes ..."; continue; };
        fi;
        echo "[+] Fixing from ${ivers} to ${cver} ...";
        brew cask uninstall "${app}" --force;
        brew cask install "${app}";
    done
    brew cask cleanup
    echo "Done"
    fi
    # Update all langenvs
    for target in "${!langenvs[@]}"; do
      if [[ -d ~/.${target} ]]; then
        langenv ${langenvs[$target]} ${target}
      fi
    done
    if hash atom 2>/dev/null; then
      echo "Updating atom plugins"
      apm upgrade -c false
    fi
  ;;

  *)
    echo "Possible args:"
    echo "env - deploy basic dotfiles"
    echo "devenv - deploy pyenv/rbenv/nodenv"
    echo "homebrew - install homebrew and favourite packages"
    echo "nuke - remove all symlinks, devenv and shell history"
    echo "housekeeper - upgrade homebrew and devenv"
esac
