" iptables syntax
if getline(1) =~ "^# Generated by iptables-save" ||  getline(1) =~ "^# Firewall configuration written by" 
  setfiletype iptables 
  set commentstring=#%s 
  finish 
endif
" sh detection
if getline(1) =~ "^#!/bin/bash" || getline(1) =~ "^#!/bin/sh"
    setfiletype sh
    finish
endif
" perl
if getline(1) =~ "^#!/usr/bin/perl" || getline(1) =~ "^#!/usr/local/bin/perl" || getline(1) =~ "^#/usr/bin/env perl"
    setfiletype perl
    finish
endif
